---
title: cv+resume
author: ''
date: '2021-04-22'
slug: resume
categories: []
tags: []
output:
  blogdown::html_page:
    toc_depth: 3
    css: "/css/my-resume.css"
---
Site: The Bishop Strachan School
Position: Data Analyst
 
Dear Manager 

I am writing to express my keen interest in Data Analyst position in the Bishop Strachan School.

I graduated from the Bio-statistics master program in the year 2019 and started to work in TD bank as Data Support Analysis. My passion and motivation came from assisting shareholder make decision from data-driven outcomes and tutoring in subject: elementary programming, math, elementary statitiscs. I have both experience in tutoring both students in lower level university and elementary school. I belief the best way to learn is trying to teach. 

In the past 6 years, I had gained data analysis experience in many topics. The most regarded was the analysis the effect of parental education to the children sodium intake. Additionally, I attended cases competition and made poster presentation in Statistics Society Conference, year 2018,2019.  Besides, my qualifications include a strong knowledge of data analysis with R and algorithms developing, code packing, writing and a complete understanding of the organizational data schema. I am willing to work with investigators and colleagues in your educational organization.

Outsite the wokring hour, I love reading people's blogs and writing my own to share ideas and make friends. Also, I master in Guzheng( a cheese instrument) and trying hard to learn Ukulele. If you would like to know me,  please reach out by email ytlinglin@gmail.com or calling 14168411903. I look forward to your reply.

Sincerely

Ling Lin


# KEY

- Experience with parametric and no parametric stimulation study. 
- Experience in experimental design, sample size calculation, Analysis of Variance(ABtesting). 
- Experience with computer programming (Python, or R).
- Be able to work independently and meet deadlines. 

# PROFESSIONAL EXPERIENCE

## Senior Data Analyst, TD Securities

### 2020.May-2020.Dec

Built dashboards for detecting data accuracy and performing quality checks and performing ad-hoc analysis and data extraction requests for reporting. Wrote python scripts to build tools for support team automated reports for downstream users based on any SQL query and distribution list. Wrote python scripts to find any computing error from many EOD batch job log files and catch any API initialization issue. Enabled employee provision by assisting managers onboarding data and collecting related new hire information; document the process.

## Data Analyst, TD Securities
### 2019.Sep-2020.Apr
Worked on a CIHR funded project to analyze the 2004 and 2015 Canadian Community Health Survey (CCHS). The analyses examined the association of sodium consumption of children (3-9years) across parental education. Used SAS to clean data and filter large multi data set contexts of large nutrition surveys. Built a table of result from un-adjusted, partially and fully adjusted model coefficient. 

## Research Analysis, Public Health Ontario
### 2018.Nov-2019.Jun
 2017  Dean's Undergraduate Research Award - NSERC 
This award enables undergraduate students to gain hands-on research experience under the supervision of one of York’s funded faculty members. Developed an algorithm of using the bootstrap method to determine the Bartlett correct factor for the one-way ANOVA model and compared the results to the standard F-test.


## Teaching Assistant, University of Toronto             
#### 2018.Sep -2019.Sep
Took on duties like grading, demonstrating labs, running a variety of tutorials, holding consultation hours, invigilating tests and exams, and a bevy of clerical duties related to course management (e.g. updating content on course websites like Quercus).


# PRESENTATION
## How To Automate Cells Counting From Microscopic Images  
### 2019 Summer
This data set contains 3,600 images and were randomly assigned to 2,400 images in 
training set and 1,200 images in validation data set. Predicted the number of cells with given
black and white pictures with Le-net architecture in __Keras__ Library. Modeled with stain 
level (2 levels) stratification prediction accuracy achieved 98.1 percent. 

## Can a Newly Published TED Talk Become Popular in The Future
### 2018 Summer
The data are from TED and extracted from the ted talk website with the different formats, 
with 2550 observations and 17 variables. Transformed the raw data for descriptive 
analysis. Applied logistics regression along with both LASSO shrinkage method and 
Forward/Backward Step wise method to select features. Compared the result with output 
from Neural Network

# EDUCATION
* University of Toronto, Biostatistics, Master of Science
* York University, Statistics, Bachelor of art, (Honor degree)








