---
title: Meta Analysis
author: ''
date: '2021-07-09'
slug: meta-analysis
categories:
  - learn
tags: []
---

[ref](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3049418/)

NOTE: most words are from the ref above, and it is a mini summary from my own perspective. Since I am truly not able to find the better word to describe.

Meta Analysis is a method used the data results from individual studies.
Studies are coming from computerized Literature Search of a database such as PudMed etc.
The auto search are based on the participants, interventions, comparison and study designs indicated in the contrasts of the scientific papers.
Comparing with the computerized search, author also mentions the other two ways: hand search, cross check the reference and communicate with the researches in the relative areas. 

In terms of the statistical analysis, for dichotomous data, risk ratio and odds ratio are used as a measurement to test the treatment effect while standardized mean difference are used on the continuous data. Then, usually a fixed effect or random effect model needs to be choose. The main difference is that fixed effect model assumes the study population, subject selection criteria and treatments are all the same and [Mantel Haenzel method](https://www.statsdirect.com/help/meta_analysis/peto.htm) and [the peto method](https://www.statsdirect.com/help/meta_analysis/mh.htm)  is used with the dichotomous data. When the statistical heterogeneity is presented after the meta analysis, the fixed effect is unsuitable and random effect models are used with an underlying assumption so it is usually more conservative with wider confidence interval than the fixed effect model.The most used random effect method is the [DerSiminian and Laird method](https://bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R/pooling-es.html#rem). 

Heterogeneity, the sources of H are two: 1 called clinical diversity and 2 called method diversity. 1 indicated the participants, outcome study, and 2 is about study design and risk of bias. 1 is more easy adjusted than 2 because 2 some times suffer from the degree of bias which are from the purposed of the study.  

Variance among K trials are usually assessed using the Cohran's Q statistics and a chi test of heterogeneity with k-1 degree of freedom. When the number of trial is small, the power is poor, thus the alpha is used 0.1 to test the hypothesis. 

The best quantitative measurement of variance is called inconsistency Index ($I^2$) when it has value larger than 75%, it is considered a large heterogeneity. Some other methods are used to check the H, the 1. meta regression, y~n. 2. subgroup analysis. a variation on those groups described above , age and sex to compare the effect group. [Forest plot](https://bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R/forest.html) is used and will add an section to demonstrate the usage of the method. 

Biased in meta analysis can be sometime illustrated by a [funnel plot](https://en.wikipedia.org/wiki/Funnel_plot).

The difference between 1 diag---nostic and 2 prog---nostic. 1 diagnose a specific disease. 2. the likelihood of developing the certain disease.  

